server:
  port: 81

spring:
  application:
    name: cloud-consumer-openfeign-order

  cloud:
    ###Consul###
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    ###Openfeign###
    openfeign:
      client:
        config:
          default:
            connectTimeout: 20000
            readTimeout: 20000

      httpclient:
        hc5:
          enabled: true

      compression:
        request:
          enabled: true
          min-request-size: 2048
        response:
          enabled: true
      ###CircuitBreaker###
      circuitbreaker:
        enabled: true
        group:
          enabled: true

# feign日志以什么级别监控哪个接口
logging:
  level:
    com:
      yc:
        cloud:
          api:
            PayApi: debug

resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 2          #在一次刷新周期内，允许执行的最大请求数
        limitRefreshPeriod: 1s     #限流器每隔limitRefreshPeriod刷新一次，将允许处理的最大请求数量重置为limitForPeriod
        timeout-duration: 1        #线程等待权限的默认等待时间
    instances:
      cloud-payment-service:
        baseConfig: default
#  bulkhead:
#    configs:
#      default:
#        maxConcurrentCalls: 2  #隔离允许并发线程执行的最大数量
#        maxWaitDuration: 1s    #当达到并发调用数量时，新的线程的阻塞时间
#  circuitbreaker:
#    configs:
#      default:
#        failureRateThreshold: 50                            #设置50%的调用失败时打开断路器，超过失败请求百分比CircuitBreaker变为OPEN状态
#        slidingWindowType: COUNT_BASED                      #滑动窗口的类型
#        slidingWindowSize: 6                                #滑动窗⼝的⼤⼩配置COUNT_BASED表示6个请求，配置TIME_BASED表示6秒
#        minimumNumberOfCalls: 6                             #断路器计算失败率或慢调用率之前所需的最小样本(每个滑动窗口周期)。如果minimumNumberOfCalls为10，则必须最少记录10个样本，然后才能计算失败率。如果只记录了9次调用，即使所有9次调用都失败，断路器也不会开启。
#        automaticTransitionFromOpenToHalfOpenEnabled: true  #是否启用自动从开启状态过渡到半开状态，默认值为true。如果启用，CircuitBreaker将自动从开启状态过渡到半开状态，并允许一些请求通过以测试服务是否恢复正常
#        waitDurationInOpenState: 5s                         #从OPEN到HALF_OPEN状态需要等待的时间
#        permittedNumberOfCallsInHalfOpenState: 2            #半开状态允许的最大请求数，默认值为10。在半开状态下，CircuitBreaker将允许最多permittedNumberOfCallsInHalfOpenState个请求通过，如果其中有任何一个请求失败，CircuitBreaker将重新进入开启状态。
#        recordExceptions:
#          - java.lang.Exception
#    instances:
#      cloud-payment-service:
#        baseConfig: default
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 20s
#thread-pool-bulkhead:
#  configs:
#    default:
#      core-thread-pool-size: 1
#      max-thread-pool-size: 1
#      queue-capacity: 1
#  instances:
#    cloud-payment-service:
#      baseConfig: default
# spring.cloud.openfeign.circuitbreaker.group.enabled 请设置为false 新启线程和原来主线程脱离

# zipkin图形展现地址和采样率设置
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #采样率默认为0.1(0.1就是10次只能有一次被记录下来)，值越大收集越及时。

